# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f969bd0faeda521547066d766dfd8453c4a6341def53f811c3af35a94c09e9778e5b722e7bb49dcff9b44398f244db3d5621a5263e34ab9237327bca23e2ad0

test:
  secret_key_base: 446f2b7c6cebee359a369fc9a1f9ae1f910f8dde0e04aee112a2fd0f4acf60c3b6ea55193b5895887151f8d134d4e7d59e73fc742839a897aa194ff265954d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
